export const siteConfig = {
  title: "O Castelo, o Ouro e o Porão",
  author: "Nide Souza",
  purchaseHref: "#leitura",
} as const;

export const copy = {
  fold1: {
    heading:
      "Eu não sabia que alguns dos sonhos que estava construindo também seriam os lugares onde eu aprenderia a perder.",
    cadence: ["Eu trabalhei.", "Empreendi.", "Criei filhos.", "Construí projetos."],
    body: [
      "Tomei decisões acreditando que estava fazendo o melhor que podia.",
      "Algumas coisas deram certo.",
      "Outras me levaram para lugares que eu jamais teria escolhido.",
    ],
    waiting: ["Houve perdas.", "Projetos que não chegaram onde eu imaginava."],
    close: [
      "Mas essa não é uma história sobre uma mulher que perdeu.",
      "É sobre uma mulher que continuou tentando construir o próprio caminho mesmo quando já não sabia exatamente onde chegaria.",
    ],
    question: "",
    signature: "",
  },
  fold2: {
    heading: "Continuar, para mim, quase sempre significou dar conta da vida que estava diante de mim.",
    cadence: ["Ser mãe.", "Trabalhar.", "Encontrar maneiras de ganhar dinheiro.", "Criar projetos."],
    body: [
      "Tomar decisões sem ter certeza de que eram as melhores.",
      "Nem sempre havia tempo para compreender uma perda antes que outra coisa precisasse ser resolvida.",
      "Os filhos continuavam precisando de mim.",
      "As contas continuavam chegando.",
      "As decisões continuavam esperando.",
      "E eu continuava também.",
    ],
  },
  fold3: {
    heading: "Durante muito tempo, achei que dar conta era o mesmo que estar bem.",
    body: [
      "Eu levantava.",
      "Trabalhava.",
      "Resolvia.",
      "Seguia.",
      "E, olhando de fora, talvez parecesse mesmo que eu sabia exatamente o que estava fazendo.",
      "Mas existe muita coisa que uma mulher consegue esconder enquanto continua funcionando.",
      "Eu mesma demorei para perceber algumas delas.",
    ],
    note: "Quando você passa tanto tempo tentando manter tudo de pé, quase não sobra espaço para se perguntar:\nE o que estava ficando de mim no meio de tudo aquilo?\nEssa pergunta não chegou de uma vez.\nMas, quando chegou, já não foi tão fácil continuar sem escutá-la.",
  },
  fold4: {
    heading: "O estranho é que eu nunca me considerei uma mulher incapaz.",
    body: [
      "Quando precisava resolver, eu resolvia.",
      "Quando alguma coisa terminava, eu procurava outro caminho.",
      "Eu tomava decisões, começava projetos, assumia responsabilidades.",
      "Havia muitas provas, na minha própria vida, de que eu era capaz.",
      "E, ainda assim, existiam lugares dentro de mim onde essa certeza parecia desaparecer.",
      "Durante muito tempo, eu não percebi a contradição.",
      "Como alguém pode fazer tanta coisa — e ainda acreditar tão pouco em algumas possibilidades para si mesma?",
    ],
  },
  fold5: {
    heading: "Durante muito tempo, eu tinha uma explicação para quase tudo.",
    questions: [
      "Para algumas escolhas.",
      "Para certos medos.",
      "Para caminhos que eu seguia — e para outros dos quais me afastava.",
      "Eu não olhava para essas explicações como crenças.",
      "Para mim, eram fatos sobre quem eu era, sobre o que podia esperar da vida e sobre aquilo que parecia possível para mim.",
      "Eu acreditava nelas.",
    ],
    body: [
      "Talvez por isso tenha levado tanto tempo para perceber:",
      "algumas dessas certezas não eram tão verdadeiras quanto eu imaginava.",
    ],
  },
  fold6: {
    heading: "Eu só comecei a desconfiar dessas certezas muito tempo depois.",
    body: [
      "Não aconteceu num grande momento de revelação.",
      "A vida continuou.",
      "Eu continuei trabalhando, decidindo, tentando, acertando algumas vezes e errando outras.",
      "Mas certas perguntas começaram a permanecer.",
      "O que antes parecia óbvio já não parecia tanto.",
      "E uma pergunta, em especial, começou a me acompanhar:",
      "Em que momento eu havia decidido o que era — e o que não era — possível para mim?",
    ],
    close: ["Eu ainda não tinha a resposta.", "Mas já não conseguia voltar a acreditar em tudo do mesmo jeito."],
  },
  fold7: {
    heading: "Foi então que comecei a escrever a minha história.",
    body: [
      "No início, eu achava que sabia o que encontraria.",
      "Afinal, era a minha vida.",
      "Eu conhecia os acontecimentos, lembrava das escolhas, sabia onde alguns caminhos tinham terminado.",
      "O que eu não sabia era que conhecer os fatos não significava compreender tudo o que eu havia construído sobre eles.",
      "Conforme eu escrevia, certas lembranças começaram a ganhar outro significado.",
      "E conclusões que eu nunca havia pensado em questionar começaram a perder a força que tiveram durante tantos anos.",
      "Eu comecei a escrever pensando que estava contando a minha história.",
      "Não imaginava que ela também começaria a me contar coisas sobre mim.",
    ],
    close: "",
  },
  fold8: {
    heading: "E parte do que encontrei não estava onde eu imaginava.",
    intro: "",
    cadence: [],
    close: [
      "Eu pensava que voltaria ao passado para compreender melhor o que tinha acontecido.",
      "Mas, em certos momentos, o que mais me surpreendeu não foi o que os outros fizeram, o que eu perdi ou os caminhos que não deram certo.",
      "Foi perceber o que eu havia concluído sobre mim mesma a partir de tudo aquilo.",
      "Algumas dessas conclusões me acompanharam por tanto tempo que eu já não sabia separá-las de quem eu era.",
      "Não pareciam interpretações.",
      "Pareciam verdades.",
      "E nem todas continuaram de pé quando colocadas diante da minha própria vida.",
    ],
  },
  fold9: {
    heading: "Foi aí que partes da minha história começaram a mudar de lugar.",
    themes: [],
    body: [
      "Não porque o passado tivesse mudado.",
      "Uma escolha continuava feita.",
      "Uma perda continuava sendo uma perda.",
      "O que aconteceu não podia ser reescrito.",
      "Mas comecei a perceber que uma coisa era o que eu havia vivido. Outra era tudo o que, a partir daquilo, eu passei a acreditar sobre mim.",
      "Lembranças que durante anos funcionaram como provas contra mim começaram a perder esse lugar.",
      "Outras levantaram perguntas que eu nunca havia feito.",
      "E certezas antigas já não pareciam tão certas.",
      "Quanto mais eu escrevia, menos aquela história cabia na versão que eu havia contado para mim mesma.",
      "E foi aí que escrever deixou de ser apenas uma maneira de contar o que aconteceu.",
    ],
    cta: "QUERO CONHECER ESSA HISTÓRIA",
  },
  fold10: {
    heading: "Escrever este livro acabou se tornando algo muito diferente do que eu imaginava.",
    body: [
      "Comecei querendo contar uma história que conhecia.",
      "Terminei descobrindo que ainda havia muito nela que eu nunca tinha compreendido.",
      "Foi desse encontro que nasceu:",
      "O Castelo, o Ouro e o Porão",
      "Uma história real.",
      "E parte do que encontrei pelo caminho ficou para as páginas deste livro.",
    ],
    cta: "QUERO CONHECER ESSA HISTÓRIA",
  },
  fold11: {
    eyebrow: "OFERTA",
    heading: "O CASTELO, O OURO E O PORÃO",
    title: "O Castelo, o Ouro e o Porão",
    format: "Livro digital — edição completa",
    description:
      "A história completa de uma mulher comum que começou a escrever acreditando que conhecia a própria vida — e descobriu que ainda havia muito nela que nunca havia compreendido.",
    price: "R$ 29,90",
    cta: "QUERO LER O LIVRO",
    security: "Livro digital • Compra segura",
  },
  author: {
    eyebrow: "QUEM ESCREVEU ESTA HISTÓRIA",
    name: "Nide Souza",
    introduction: "Mulher, mãe, empreendedora e, agora, escritora.",
    body: [
      "O Castelo, o Ouro e o Porão nasceu quando decidiu voltar à própria história não para torná-la mais bonita, mas para compreendê-la.",
      "Ao escrever, encontrou uma mulher diferente daquela que durante muitos anos acreditou ser.",
      "Este é seu primeiro livro. E esta é a sua história real.",
    ],
  },
  closingOffer: {
    title: "O CASTELO, O OURO E O PORÃO",
    format: "Livro digital — edição completa",
    price: "R$ 29,90",
    cta: "QUERO LER O LIVRO",
    security: "Livro digital • Compra segura",
  },
} as const;
